#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : grilo
Version  : 0.3.15
Release  : 23
URL      : https://download.gnome.org/sources/grilo/0.3/grilo-0.3.15.tar.xz
Source0  : https://download.gnome.org/sources/grilo/0.3/grilo-0.3.15.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: grilo-bin = %{version}-%{release}
Requires: grilo-data = %{version}-%{release}
Requires: grilo-lib = %{version}-%{release}
Requires: grilo-license = %{version}-%{release}
Requires: grilo-locales = %{version}-%{release}
Requires: grilo-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : gsettings-desktop-schemas
BuildRequires : liboauth-dev
BuildRequires : pkgconfig(libsoup-3.0)
BuildRequires : pkgconfig(oauth)
BuildRequires : totem-pl-parser-dev

%description
# Grilo
Thanks for using Grilo!
## What is Grilo?
Grilo is a framework for browsing and searching media content from various
sources using a single API.

%package bin
Summary: bin components for the grilo package.
Group: Binaries
Requires: grilo-data = %{version}-%{release}
Requires: grilo-license = %{version}-%{release}

%description bin
bin components for the grilo package.


%package data
Summary: data components for the grilo package.
Group: Data

%description data
data components for the grilo package.


%package dev
Summary: dev components for the grilo package.
Group: Development
Requires: grilo-lib = %{version}-%{release}
Requires: grilo-bin = %{version}-%{release}
Requires: grilo-data = %{version}-%{release}
Provides: grilo-devel = %{version}-%{release}
Requires: grilo = %{version}-%{release}

%description dev
dev components for the grilo package.


%package doc
Summary: doc components for the grilo package.
Group: Documentation
Requires: grilo-man = %{version}-%{release}

%description doc
doc components for the grilo package.


%package lib
Summary: lib components for the grilo package.
Group: Libraries
Requires: grilo-data = %{version}-%{release}
Requires: grilo-license = %{version}-%{release}

%description lib
lib components for the grilo package.


%package license
Summary: license components for the grilo package.
Group: Default

%description license
license components for the grilo package.


%package locales
Summary: locales components for the grilo package.
Group: Default

%description locales
locales components for the grilo package.


%package man
Summary: man components for the grilo package.
Group: Default

%description man
man components for the grilo package.


%prep
%setup -q -n grilo-0.3.15
cd %{_builddir}/grilo-0.3.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664938880
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Denable-grl-pls=true  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
# Tests require some glib schemas to be initialized
target=$HOME/.local/share/glib-2.0/schemas
mkdir -p $target
glib-compile-schemas --targetdir=$target /usr/share/glib-2.0/schemas
export XDG_DATA_DIRS="$HOME/.local/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/grilo
cp %{_builddir}/grilo-%{version}/COPYING %{buildroot}/usr/share/package-licenses/grilo/caeb68c46fa36651acf592771d09de7937926bb3 || :
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang grilo

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/grilo-test-ui-0.3
/usr/bin/grl-inspect-0.3
/usr/bin/grl-launch-0.3

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Grl-0.3.typelib
/usr/lib64/girepository-1.0/GrlNet-0.3.typelib
/usr/lib64/girepository-1.0/GrlPls-0.3.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/grilo-0.3.deps
/usr/share/vala/vapi/grilo-0.3.vapi
/usr/share/vala/vapi/grilo-net-0.3.deps
/usr/share/vala/vapi/grilo-net-0.3.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/grilo-0.3/grilo.h
/usr/include/grilo-0.3/grl-caps.h
/usr/include/grilo-0.3/grl-config.h
/usr/include/grilo-0.3/grl-data.h
/usr/include/grilo-0.3/grl-definitions.h
/usr/include/grilo-0.3/grl-error.h
/usr/include/grilo-0.3/grl-log.h
/usr/include/grilo-0.3/grl-media.h
/usr/include/grilo-0.3/grl-metadata-key.h
/usr/include/grilo-0.3/grl-multiple.h
/usr/include/grilo-0.3/grl-operation-options.h
/usr/include/grilo-0.3/grl-operation.h
/usr/include/grilo-0.3/grl-plugin.h
/usr/include/grilo-0.3/grl-range-value.h
/usr/include/grilo-0.3/grl-registry.h
/usr/include/grilo-0.3/grl-related-keys.h
/usr/include/grilo-0.3/grl-source.h
/usr/include/grilo-0.3/grl-util.h
/usr/include/grilo-0.3/grl-value-helper.h
/usr/include/grilo-0.3/net/grl-net-wc.h
/usr/include/grilo-0.3/net/grl-net.h
/usr/include/grilo-0.3/pls/grl-pls.h
/usr/lib64/libgrilo-0.3.so
/usr/lib64/libgrlnet-0.3.so
/usr/lib64/libgrlpls-0.3.so
/usr/lib64/pkgconfig/grilo-0.3.pc
/usr/lib64/pkgconfig/grilo-net-0.3.pc
/usr/lib64/pkgconfig/grilo-pls-0.3.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/grilo/GrlCaps.html
/usr/share/gtk-doc/html/grilo/GrlConfig.html
/usr/share/gtk-doc/html/grilo/GrlData.html
/usr/share/gtk-doc/html/grilo/GrlMedia.html
/usr/share/gtk-doc/html/grilo/GrlOperationOptions.html
/usr/share/gtk-doc/html/grilo/GrlPlugin.html
/usr/share/gtk-doc/html/grilo/GrlRegistry.html
/usr/share/gtk-doc/html/grilo/GrlRelatedKeys.html
/usr/share/gtk-doc/html/grilo/GrlSource.html
/usr/share/gtk-doc/html/grilo/annotation-glossary.html
/usr/share/gtk-doc/html/grilo/api-index-full.html
/usr/share/gtk-doc/html/grilo/caps-options.html
/usr/share/gtk-doc/html/grilo/ch01.html
/usr/share/gtk-doc/html/grilo/ch02.html
/usr/share/gtk-doc/html/grilo/ch03.html
/usr/share/gtk-doc/html/grilo/ch04.html
/usr/share/gtk-doc/html/grilo/configure.html
/usr/share/gtk-doc/html/grilo/data.html
/usr/share/gtk-doc/html/grilo/deprecated-api-index.html
/usr/share/gtk-doc/html/grilo/grilo-GrlNetWc.html
/usr/share/gtk-doc/html/grilo/grilo-GrlPls.html
/usr/share/gtk-doc/html/grilo/grilo-Multiple.html
/usr/share/gtk-doc/html/grilo/grilo-grilo.html
/usr/share/gtk-doc/html/grilo/grilo-grl-definitions.html
/usr/share/gtk-doc/html/grilo/grilo-grl-error.html
/usr/share/gtk-doc/html/grilo/grilo-grl-log.html
/usr/share/gtk-doc/html/grilo/grilo-grl-metadata-key.html
/usr/share/gtk-doc/html/grilo/grilo-grl-operation.html
/usr/share/gtk-doc/html/grilo/grilo-grl-util.html
/usr/share/gtk-doc/html/grilo/grilo-net.html
/usr/share/gtk-doc/html/grilo/grilo-pls.html
/usr/share/gtk-doc/html/grilo/grilo.devhelp2
/usr/share/gtk-doc/html/grilo/home.png
/usr/share/gtk-doc/html/grilo/index.html
/usr/share/gtk-doc/html/grilo/left-insensitive.png
/usr/share/gtk-doc/html/grilo/left.png
/usr/share/gtk-doc/html/grilo/misc.html
/usr/share/gtk-doc/html/grilo/multiple.html
/usr/share/gtk-doc/html/grilo/plugin-management.html
/usr/share/gtk-doc/html/grilo/pr01.html
/usr/share/gtk-doc/html/grilo/right-insensitive.png
/usr/share/gtk-doc/html/grilo/right.png
/usr/share/gtk-doc/html/grilo/rn01.html
/usr/share/gtk-doc/html/grilo/rn02.html
/usr/share/gtk-doc/html/grilo/rn03.html
/usr/share/gtk-doc/html/grilo/rn04.html
/usr/share/gtk-doc/html/grilo/sources.html
/usr/share/gtk-doc/html/grilo/style.css
/usr/share/gtk-doc/html/grilo/up-insensitive.png
/usr/share/gtk-doc/html/grilo/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgrilo-0.3.so.0
/usr/lib64/libgrilo-0.3.so.0.315.1
/usr/lib64/libgrlnet-0.3.so.0
/usr/lib64/libgrlnet-0.3.so.0.315.0
/usr/lib64/libgrlpls-0.3.so.0
/usr/lib64/libgrlpls-0.3.so.0.315.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/grilo/caeb68c46fa36651acf592771d09de7937926bb3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/grilo-test-ui-0.3.1
/usr/share/man/man1/grl-inspect-0.3.1
/usr/share/man/man1/grl-launch-0.3.1

%files locales -f grilo.lang
%defattr(-,root,root,-)

